# Generated by Django 4.2.3 on 2023-08-10 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.CharField(max_length=1000)),
                ('pay', models.CharField(max_length=10)),
                ('location', models.CharField(max_length=200)),
                ('duration', models.CharField(max_length=50)),
                ('application_date', models.DateField()),
                ('application_deadline', models.DateField()),
            ],
        ),
    ]
