# Generated by Django 4.2.3 on 2023-09-06 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_alter_job_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jobtype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
            ],
        ),
        migrations.AddField(
            model_name='job',
            name='jobtype',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='job.jobtype'),
        ),
    ]
